"""
Django settings for jobnix project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Load environment variables
load_dotenv()

# BASE DIRECTORY
BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================
#  SECURITY & DEBUG SETTINGS
# ==============================

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-temp-key')
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.vercel.app',
    '.ngrok-free.app',
    '.ngrok-free.dev',
    'jobnix.onrender.com',
]

CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://*.ngrok-free.dev',
    'https://*.vercel.app',
    'https://jobnix.onrender.com',
]


# ==============================
#  APPLICATION CONFIGURATION
# ==============================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Project apps
    'jobs',
    'accounts.apps.AccountsConfig',
    'admin_panel',
    'analytics',
    'education',
    'mentors',
]

AUTH_USER_MODEL = 'accounts.User'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # static file optimization
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'jobnix.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jobnix.wsgi.application'


# ==============================
#  DATABASE CONFIGURATION
# ==============================

# ==============================
#  DATABASE CONFIGURATION
# ==============================

# Use PostgreSQL from Render (production)
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    # Fallback for local development (you can use SQLite for simplicity)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Fallback for local dev
# if not DATABASES['default']:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.mysql',
#             'NAME': os.getenv("DB_NAME", "jobnix"),
#             'USER': os.getenv("DB_USER", "jobnix"),
#             'PASSWORD': os.getenv("DB_PASSWORD", "success"),
#             'HOST': os.getenv("DB_HOST", "localhost"),
#             'PORT': os.getenv("DB_PORT", "3306"),
#         }
#     }


# ==============================
#  PASSWORD VALIDATION
# ==============================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ==============================
#  INTERNATIONALIZATION
# ==============================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ==============================
#  LOGIN / LOGOUT REDIRECTS
# ==============================

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'accounts:dashboard'
LOGOUT_REDIRECT_URL = 'landing'


# ==============================
#  STATIC & MEDIA FILES
# ==============================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ==============================
#  EMAIL CONFIGURATION (Resend API + Fallbacks)
# ==============================

# Default to console backend for safety
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Resend API Configuration
RESEND_API_KEY = os.getenv('RESEND_API_KEY', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'JobNix <onboarding@resend.dev>')

# Only use SMTP if explicitly configured for Gmail/other provider
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

# If Gmail SMTP credentials are provided, use SMTP backend
if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD and EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    print(f"✅ Using SMTP backend with {EMAIL_HOST}")
elif RESEND_API_KEY:
    # We have Resend API key, but we'll handle it in utils.py
    print("✅ Resend API key found - API-based email sending enabled")
else:
    print("⚠️  Using console email backend - emails will be printed to logs")
    print("⚠️  To enable real emails, add RESEND_API_KEY or SMTP credentials to .env")


# ==============================
#  FRONTEND CONFIGURATION
# ==============================

FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://jobnix.onrender.com')


# ==============================
#  ADMIN DEFAULTS
# ==============================

ADMIN_EMAIL = os.getenv('ADMIN_EMAIL', 'ndegwaanthony300@gmail.com')
ADMIN_PASSWORD = os.getenv('ADMIN_PASSWORD', 'Sucess@123')


# ==============================
#  DEFAULT AUTO FIELD
# ==============================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
