# Generated by Django 5.2.7 on 2025-11-02 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='education.course')),
            ],
            options={
                'db_table': 'course_modules',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('document', 'Document'), ('link', 'External Link'), ('text', 'Text Content'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], default='video', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, or other video URL')),
                ('video_file', models.FileField(blank=True, help_text='Upload video file', null=True, upload_to='course_videos/')),
                ('video_duration', models.CharField(blank=True, help_text="e.g., '10:30'", max_length=20)),
                ('document_file', models.FileField(blank=True, help_text='PDF, DOC, etc.', null=True, upload_to='course_documents/')),
                ('document_url', models.URLField(blank=True, help_text='External document link')),
                ('external_link', models.URLField(blank=True, help_text='External resource link')),
                ('link_title', models.CharField(blank=True, max_length=200)),
                ('text_content', models.TextField(blank=True, help_text='Text/HTML content')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_free_preview', models.BooleanField(default=False, help_text='Available without enrollment')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Content duration in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='education.course')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='education.coursemodule')),
            ],
            options={
                'db_table': 'course_contents',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
