# Generated by Django 5.2.7 on 2025-11-04 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text='Professional background and expertise')),
                ('expertise_areas', models.TextField(help_text='Comma-separated areas of expertise (e.g., Software Development, Business, Marketing)')),
                ('years_of_experience', models.IntegerField(default=0)),
                ('current_position', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('languages', models.CharField(default='English', help_text='Languages spoken (comma-separated)', max_length=200)),
                ('availability_hours', models.CharField(blank=True, help_text='e.g., Monday-Friday, 9am-5pm', max_length=200)),
                ('max_mentees', models.IntegerField(default=10, help_text='Maximum number of active mentees')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Hourly rate (0 for free mentorship)', max_digits=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from mentees', max_digits=3)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_mentees', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role__in': ['employer', 'institution']}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentors',
                'ordering': ['-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Why do you want mentorship from this mentor?')),
                ('goals', models.TextField(help_text='What are your career goals?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('match_score', models.DecimalField(decimal_places=2, default=0.0, help_text='AI-calculated compatibility score', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('mentee', models.ForeignKey(limit_choices_to={'role': 'youth'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_requests', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_requests', to='mentors.mentor')),
            ],
            options={
                'db_table': 'mentorship_requests',
                'ordering': ['-created_at'],
                'unique_together': {('mentee', 'mentor')},
            },
        ),
        migrations.CreateModel(
            name='MentorshipGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='in_progress', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('mentor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mentorship', models.ForeignKey(limit_choices_to={'status': 'accepted'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_goals', to='mentors.mentorshiprequest')),
            ],
            options={
                'db_table': 'mentorship_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('document', 'Document'), ('link', 'External Link'), ('video', 'Video'), ('article', 'Article')], default='link', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, help_text='Link to resource')),
                ('file', models.FileField(blank=True, null=True, upload_to='mentorship_resources/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentorship', models.ForeignKey(limit_choices_to={'status': 'accepted'}, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='mentors.mentorshiprequest')),
            ],
            options={
                'db_table': 'mentorship_resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom/Teams/Google Meet link')),
                ('meeting_type', models.CharField(choices=[('video', 'Video Call'), ('in_person', 'In Person'), ('phone', 'Phone Call')], default='video', max_length=50)),
                ('agenda', models.TextField(blank=True, help_text='Session agenda or topics to discuss')),
                ('notes', models.TextField(blank=True, help_text='Session notes (filled after session)')),
                ('feedback', models.TextField(blank=True, help_text='Mentor feedback')),
                ('rating', models.IntegerField(blank=True, help_text='Mentee rating (1-5)', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentorship', models.ForeignKey(limit_choices_to={'status': 'accepted'}, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mentors.mentorshiprequest')),
            ],
            options={
                'db_table': 'mentorship_sessions',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
